# Generated by Django 5.2.6 on 2025-09-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Add_students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_num", models.IntegerField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("department", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=20)),
            ],
        ),
    ]
